name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      runner_type:
        description: "Runner type: 'self-hosted' (default) or 'github-hosted'"
        type: choice
        default: self-hosted
        options:
          - self-hosted
          - github-hosted

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ${{ inputs.runner_type == 'github-hosted' && 'arm-runner' || fromJSON('["self-hosted","ARM64"]') }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
